config/routes.rb
BayAutomationDepartment::Engine.routes.draw do

  resources :example, only: [:index, :new, :create]

end

app/models/bay_automation_department/application_record.rb
module BayAutomationDepartment
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/bay_automation_department/application_controller.rb
module BayAutomationDepartment
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper BayBootstrapHelper
  end
end

app/controllers/bay_automation_department/example_controller.rb
require_dependency "bay_automation_department/application_controller"

module BayAutomationDepartment
  class ExampleController < ApplicationController

    # GET
    def index
      @upload_form = Upload.new
      render :new
    end

    # GET
    def new
      @upload_form = Upload.new
    end

    # POST
    def create
      @upload_form = Upload.new(upload_params)
      respond_to do |format|
        if @upload_form.submit
          doc = @upload_form.process
          @str = doc.to_html
          format.html { render :layout => false }
        else
          format.html { render :new }
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      properties_keys = params[:upload].try(:fetch, :parameters, {}).keys
      params.require(:upload).permit(:file, parameters: properties_keys)
    end

  end
end

app/helpers/bay_automation_department/application_helper.rb
module BayAutomationDepartment
  module ApplicationHelper
  end
end

app/views/bay_automation_department/_parameters.html.erb
  <div class="field">
    <label>Department</label>
    <%= content_tag :span, {class: "glyphicon glyphicon-info-sign", data: {toggle: "tooltip", placement: "right" }, title: "Name of the department"} do %>
    <% end %>
    <br>
    <%= f.text_field :title  %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= content_tag :span, {class: "glyphicon glyphicon-info-sign", data: {toggle: "tooltip", placement: "right" }, title: "The color in hex. e.g. #CDCDCD"} do %>
    <% end %>
    <br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :classname %><br>
    <%= content_tag :span, {class: "glyphicon glyphicon-info-sign", data: {toggle: "tooltip", placement: "right" }, title: "Additional class to append"} do %>
    <% end %>
    <br>
    <%= f.text_field :classname %>
  </div>
  <div id="breadcrumb_text_field" class="field">
    <label>Breadcrumbs</label>
    <%= content_tag :span, {class: "glyphicon glyphicon-info-sign", data: {toggle: "tooltip", placement: "right" }, title: "Name of the department"} do %>
    <% end %>
    <br>
    <%= f.text_field :breadcrumbs, :class=>"tokenfield"  %>
  </div>

app/views/bay_automation_department/example/create.html.erb
<%= @str.html_safe %>

app/views/bay_automation_department/example/new.html.erb
<%= form_wrap do -%>
  <%= form_for(@upload_form, url: example_index_path ) do |f| %>
    <div class="field">
      <%= f.label :file %><br>
      <%= f.file_field :file %>
    </div>

    <%= f.fields_for :parameters, f.object.parameter_object do |param_field| %>
      <%= render :partial => 'bay_automation_department/parameters', locals: { f: param_field } %>
    <% end %>

    <%= f.submit %>
  <% end %>

<% end %>

app/views/layouts/bay_automation_department/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bay automation department</title>
  <%= stylesheet_link_tag    "bay_automation_department/application", media: "all" %>
  <%= javascript_include_tag "bay_automation_department/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>